version: '3.8'
services:
  valhalla:
    image: ghcr.io/gis-ops/docker-valhalla/valhalla:latest
    container_name: valhalla
    ports:
      - "8002:8002"
    volumes:
      - valhalla-data:/custom_files
    environment:
      - build_elevation=False
      - build_admins=True
      - build_time_zones=True
      - use_tiles_ignore_pbf=True
      - force_rebuild=False
    restart: always

volumes:
  valhalla-data:
